# Tutorial 2a. Tensors

- Tensors are one of the main ingredients when it comes to modern Deep-Learning frameworks. 
- Almost all deep learning computations can be expressed as tensor operations which make computation fast and efficient. 
- In this practical we will see how to manipulate tensors within the `PyTorch` library

You'll need to install `pytorch` using `conda install torch` or `pip install torch` on your laptop

In [2]:
import torch
import numpy as np

## Basics with tensors

In [3]:
# Generate a tensor of size 2x3x4
t = torch.Tensor(2, 3, 4)
print(t)

tensor([[[-7.0111e+19,  4.5744e-41,  1.5414e-44,  4.1878e-38],
         [ 0.0000e+00,  0.0000e+00,  1.1210e-44,  0.0000e+00],
         [ 0.0000e+00,  4.1880e-38,  1.1097e-35,  1.6826e-37]],

        [[ 6.7011e-37,  3.7813e+00,  2.6805e-36,  4.7757e-38],
         [ 4.2886e-35,  2.8532e-33,  9.5190e-41,  1.7154e-34],
         [ 4.5652e-32,  1.8261e-31,  7.3046e-31,  2.9219e-30]]])


In [4]:
# Get the type of the tensor
t.type()

'torch.FloatTensor'

In [5]:
# Get information about the tensor
print(t.size())
print(t.shape)
print(t.numel())
print(t.dim())

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])
24
3


In [6]:
# Resize the tensor
r = torch.Tensor(t)
r.resize_(3, 8)
print(r)
print(r.size())

tensor([[-7.0111e+19,  4.5744e-41,  1.5414e-44,  4.1878e-38,  0.0000e+00,
          0.0000e+00,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  4.1880e-38,  1.1097e-35,  1.6826e-37,  6.7011e-37,
          3.7813e+00,  2.6805e-36,  4.7757e-38],
        [ 4.2886e-35,  2.8532e-33,  9.5190e-41,  1.7154e-34,  4.5652e-32,
          1.8261e-31,  7.3046e-31,  2.9219e-30]])
torch.Size([3, 8])


## Vectors (1D Tensors) and similarities with Numpy

- You might have noticed some similarities between the way PyTorch deals with tensors and the way Numpy deals with arrays
- When it comes to basic algebraic operations both libraries can indeed be very similar as shown in some of the examples below

In [7]:
# Creates a 1D tensor of integers 1 to 4
v = torch.Tensor([1, 2, 3, 4])
np_v = np.array([1, 2, 3, 4])

print(v)
print(np_v)

tensor([1., 2., 3., 4.])
[1 2 3 4]


Note however the difference with the default `dtypes` used

In [8]:
v.dtype, np_v.dtype

(torch.float32, dtype('int64'))

In [9]:
# We create a second tensor with the same properties
w = torch.Tensor([1, 0, 2, 0])
np_w = np.array([1, 0, 2, 0])

print(w)
print(np_w)

tensor([1., 0., 2., 0.])
[1 0 2 0]


In [10]:
# Element-wise multiplication
x = v * w
np_x = np_v * np_w

print(x)
print(np_x)

tensor([1., 0., 6., 0.])
[1 0 6 0]


In [11]:
# Slicing: extract sub-Tensor [from:to)
print(x[0:3])
print(np_x[0:3])

tensor([1., 0., 6.])
[1 0 6]


In [12]:
# Create a tensor with integers ranging from 1 to 5, excluding 5
v = torch.arange(1, 4 + 1)
np_v = np.arange(1, 5)
print(v)
print(np_v)

tensor([1, 2, 3, 4])
[1 2 3 4]


In [13]:
# Square all elements in the tensor
print(v ** 2)
print(np_v ** 2)

tensor([ 1,  4,  9, 16])
[ 1  4  9 16]


But also

In [14]:
print(v.pow(2))
print(np.power(np_v, 2))

tensor([ 1,  4,  9, 16])
[ 1  4  9 16]


## Let's add one dimension: matrices (2D Tensors)

In [15]:
# Create a 2x4 tensor
m = torch.Tensor([[2, 5, 3, 7],
                  [4, 2, 1, 9]])
print(m)

np_m = np.array([[2, 5, 3, 7],[4, 2, 1, 9]])
print(np_m)

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])
[[2 5 3 7]
 [4 2 1 9]]


In [16]:
# Get the shape of the tensor
print(m.size())
print(np_m.shape)

torch.Size([2, 4])
(2, 4)


In [17]:
# Indexing row 0, column 2 (0-indexed)
m[0, 2]

tensor(3.)

In [18]:
# Indexing column 1, all rows (returns size 2)

m[:, 1]

tensor([5., 2.])

## Some easy exercises: tensor Operations

It is now up to you to get familiar with some basic tensor operations in PyTorch.

In [19]:
m.dtype

torch.float32

In [20]:
torch.Tensor()

tensor([])

In [21]:
# Indexing column 1, all rows (returns size 2x1, not 2)

m[:, [1]]

tensor([[5.],
        [2.]])

In [22]:
# Indexes row 0, all columns (returns 1x4)

m[[0], :]

tensor([[2., 5., 3., 7.]])

In [23]:
# Add a random tensor of size 2x4 to m

m + torch.rand(2, 4)

tensor([[2.4411, 5.9791, 3.9976, 7.9205],
        [4.1664, 2.6012, 1.3487, 9.0499]])

In [24]:
# Subtract a random tensor of size 2x4 to m

m - torch.rand(2, 4)

tensor([[1.4092, 4.2686, 2.1500, 6.8292],
        [3.8568, 1.3593, 0.0381, 8.6417]])

In [25]:
# Multiply a random tensor of size 2x4 to m

m * torch.rand(2, 4)

tensor([[0.1380, 3.1732, 0.0588, 6.5105],
        [1.8228, 0.3364, 0.8150, 3.5823]])

In [26]:
# Divide m by a random tensor of size 2x4

m / torch.rand(2, 4)

tensor([[  2.8657,  43.9122,  36.2250, 216.4942],
        [ 13.6966,   3.5158,   1.0701,   9.7605]])

In [29]:
# Transpose tensor m

m.t()

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

## Exercise: polynomial regression

- Last week we discussed polynomial logistic regression
- Let's work also on polynomial regression (continuous label) with a **single feature**
- In this exercise we show how this simple model can be trained using `numpy` and your work will be to code the solution with `PyTorch` 

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
def true_f(x):
    return 0.1 * (x-2) ** 3 + x ** 2 - 8.0 * x - 1.0

def generate(n_samples):
    X = np.random.rand(n_samples) * 20.0 - 10.0
    y = true_f(X) + 5 * np.random.randn(n_samples)
    
    return X.reshape(n_samples, 1), y

X_train, y_train = generate(15)
xs = np.linspace(-10, 10, num=1000)
plt.plot(xs, true_f(xs), c="r", label="$g(x)$", lw=3)
plt.scatter(X_train, y_train, label="$y = g(x) + \epsilon$")
plt.legend(loc='upper left', fontsize=13)
plt.grid(color="grey")

In [ ]:
def numpy_model(X, beta, poly):
    Xp = poly.transform(X)
    return np.dot(Xp, beta)

In [ ]:
poly = PolynomialFeatures(degree=3, include_bias=True)
Xp = poly.fit_transform(X_train)

# We use the analytic solution for the optimization problem. 
# Note that this is not something we usually do in machine learning, where 
#   we'd rather use an optimization algorithm
np_beta = np.linalg.solve(Xp.T.dot(Xp), Xp.T.dot(y_train))
 # Least-squares error
error = np.mean((y_train - numpy_model(X_train, np_beta, poly)) ** 2)
plt.plot(xs, true_f(xs), c="r", label="$g(x)$")
plt.scatter(X_train, y_train, label="$y = g(x) + \epsilon$")
plt.plot(xs, numpy_model(xs.reshape(-1,1), np_beta, poly), c="b", label="$\hat{y} = f_{numpy}(x)$")
plt.title("degree = %d, $\hat{R}(f, d) = %.2f$" % (3, error), fontsize=15)
plt.ylim(-40, 80)
plt.grid()
plt.legend(fontsize=13)
plt.show()

print("The error of our model is {}".format(error))

# PyTorch solution

The solutons consists of 2 easy steps:

* create a function similar to the model one which does the required computations in PyTorch instead of Numpy.
* Solve the optimization problem by using the 2D tensor operations we have seen before. Some of these operations require some basic transformations between Numpy arrays and PyTorch tensors.

In [ ]:
def pytorch_model(X, beta, poly):
    Xp = poly.transform(X)    
    return torch.matmul(torch.from_numpy(Xp), beta)

In [ ]:
poly = PolynomialFeatures(degree=3, include_bias=True)

Xp = poly.fit_transform(X_train)
Xpt = torch.from_numpy(Xp)

In [ ]:
XtX = torch.matmul(Xpt.t(), Xpt)
Xty = torch.matmul(Xpt.t(), torch.from_numpy(y_train))
Xty = Xty.reshape(*Xty.shape, 1)
pt_beta, _ = torch.solve(Xty, XtX)

In [ ]:
pt_beta

In [ ]:
pt_beta - np_beta

Of course, we get the exact same solutions

In [ ]:
pytorch_model(X_train, pt_beta, poly)